name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BackEnd
        
    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test


  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./BackEnd

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag desquivel501/ayd1_g6_backend
      
    - name: Push the Docker image
      run: docker push desquivel501/ayd1_g6_backend
